[workspace]
members = [
  "blokus",
  "connect4",
  "chess_",
  "qwirkle",
  "tzf8",
  "rustyai", 
  "v2",
  "cdcl",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
