// Code generated by jtd-codegen for TypeScript v0.2.1

export interface BoardState {
  over: boolean;
  remaining_tiles: Tile[];
  table: (Player | null)[][];
  player_to_move?: Player;
}

export enum Player {
  P1 = "P1",
  P2 = "P2",
  P3 = "P3",
  P4 = "P4",
}

export enum Tile {
  T1 = "T1",
  T2 = "T2",
  T3 = "T3",
  T4 = "T4",
  T5 = "T5",
  T6 = "T6",
}
